### ISSUE TITLE
Cannot generate new modpack code

### ISSUE THREAD

**Issue by naxalar** [Y0ungSandwich/LightlySalted#14]
I used lightlysalted as a modpack base and then added some of our commonly used mods on top.
However, when I click share code ATLauncher reports that nothing has changed.

If I do the same thing with Bevos Superstitions it works fine.

Is this a known issue?

**Comment by Y0ungSandwich** [comment]
No clue.  We don't support altered packs.  Something you'd have to take up with ATL support.
