### ISSUE TITLE
ModelLoader: baking takes forever then crashes

### ISSUE THREAD

**Issue by just-Bri** [Y0ungSandwich/LightlySalted#9]
I'll upload a log when back on the computer that is having this problem.

When the client hits ModelLoader: baking step cpu and ram usage spikes and each object takes about 30 seconds to load. Tried googling it, all I found was disabling splash in splash.properties but that hasn't worked.

**Comment by just-Bri** [comment]
Thank you for closing this, I meant to request a close a while ago and have been super busy moving and finding a job. Sorry!

Keep up the good work!

**Comment by Y0ungSandwich** [comment]
Good luck to you! 

We are actually taking the pack in an entirely new direction for 1.12.2 and it will be public on ATL. 
Swing by the discord and keep an eye out when ya get time!

https://discord.gg/cfrQX3v
